version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dqlab-livecode
    ports:
    - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka  
    ports:  
      - "9092:9092" 
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "submission:1:1"
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      
  livecode:
    image: dqlab-microservices-livecode:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
    - 8080:8080
    env_file: .env
    depends_on:
      - db
      - kafka

  compiler:
    privileged: true
    image: dqlab-microservices-compilers:0.0.1-SNAPSHOT
    restart: on-failure
    env_file: .env
    ports:
    - 8081:8081
    depends_on:
      - db
      - kafka

volumes:
  postgres-data:
