version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dqlab-livecode
    ports:
    - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: unless-stopped

  livecode:
    image: dqlab-microservices-livecode:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
    - 8080:8080
    environment:
      - JAVA_OPTS=
        -DDATABASE_URL=jdbc:postgresql://db:5432/dqlab-livecode?serverTimezone=UTC
        -DDATABASE_USERNAME=postgres
        -DDATABASE_PASSWORD=secret
    depends_on:
      - db

volumes:
  postgres-data: